"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = [".form[_ngcontent-%COMP%]{\r\n    padding: 20px;\r\n    margin-top: 20px;\r\n}"];
exports.styles = styles;
//# sourceMappingURL=form.component.css.shim.ngstyle.js.map